@hostname = http://localhost/rest-api-lumen-jwt/api/v1
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3RcL3Jlc3QtYXBpLWx1bWVuLWp3dFwvYXBpXC92MVwvYXV0aFwvbG9naW4iLCJpYXQiOjE2NDk0NzE4NzMsImV4cCI6MTY0OTQ3NTQ3MywibmJmIjoxNjQ5NDcxODczLCJqdGkiOiJwRlJ1M3VRR05UUG1wZUdPIiwic3ViIjoxLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.3GA4b4bf8FwWwBYCb4SND29dNcgS5TwyfzRdT6EmdgU



###### Register
POST {{hostname}}/auth/register
content-type: application/json

{
    "username"              : "hamdani",
    "password"              : "456",
    "password_confirmation" : "456",
    "email"                 : "ibnuhamdani@gmail.com",
    "country_code"          : "+62",
    "phone_number"          : "83823134571"
}


###### Login
POST {{hostname}}/auth/login
content-type: application/json

{ 
    "password" : "123",  
    "email" : "ibnuhamdani234@gmail.com"
}

######
GET {{hostname}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}

###### Quote
GET {{hostname}}/quote
Content-Type: application/json 

{
    "url" : "https://api.chucknorris.io/jokes/random"
    //"url" : "https://catfact.ninja/fact"
}


###### Transaction
POST {{hostname}}/transaction
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "trx_id"    : "d",
    "amount"    : "0.80674223",
    "user_id"   : 1
}


###### import csv
POST {{hostname}}/price/upload
Content-Type: multipart/form-data
Authorization: Bearer {{token}}

{
    "uploaded_file" : "upload file csv nya"
}


###### low-high
POST {{hostname}}/price/low-high
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "month"     : "10",
    "year"      : "2017",
    "currency"  : "usd",
    "ticker"    : "BTC"
}


###### history
POST {{hostname}}/price/history
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "start_time"    : "2017-10-08 07:00:00",
    "end_time"      : "2017-10-11 07:00:00",
    "currency"      : "usd", 
    "ticker"        : "BTC"
}